# Generated by Django 5.2.3 on 2025-07-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='map_coordinates',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
