# Generated by Django 5.2.3 on 2025-07-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_map_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='map_coordinates',
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
