# Generated by Django 5.2.3 on 2025-07-07 18:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_reference',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='purchase_id',
            field=models.CharField(default=uuid.UUID('366ae946-e759-4654-a96c-ffd28205f49e'), max_length=225),
        ),
    ]
