# Generated by Django 5.2.3 on 2025-07-05 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='address',
            new_name='delivery_address',
        ),
    ]
