# Generated by Django 5.2.3 on 2025-06-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_remove_product_size_alter_cartitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
