# Generated by Django 5.2.3 on 2025-07-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0007_alter_product_options_remove_product_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
