# Generated by Django 5.2.3 on 2025-07-04 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0012_remove_cartitem_product_remove_cartitem_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='color',
            new_name='colour',
        ),
    ]
