# Generated by Django 5.2.3 on 2025-07-08 15:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_payment_reference_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
