# Generated by Django 5.2.3 on 2025-07-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(default='ref-UNIQUE_ID', editable=False, unique=True),
        ),
    ]
