# Generated by Django 5.2.3 on 2025-07-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_cartitem_user_remove_cartitem_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('NA', 'None')], max_length=2),
        ),
    ]
